version: 2

# https://docs.getdbt.com/reference/source-properties
sources:
  - name: bq_dataset
    dataset: data_warehouse_dev # schema / dataset (bq)
    project: "{{ env_var('GCP_PROJECT') }}" # database / project (bq)
    tables:
      - name: raw_table
