version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "terraform/environments/dev/"
    schedule:
      interval: "daily"

updates:
  - package-ecosystem: "pip"
    directory: "terraform/modules/workflow-platform/"
    schedule:
      interval: "daily"
