name: dags

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dags/**.py'
  push:
    branches:
      - main
    paths:
      - 'dags/**.py'

permissions:
  contents: read

jobs:
  get-composer-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install jq
        run: sudo apt install -y jq

      - id: get-dev
        name: Get Cloud Composer bucket in dev
        run: |
          terraform init
          run: echo "::set-output name=bucket::$(terraform output -json | jq -r '.airflow_dags_gcs_prefix.value')"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        working-directory: terraform/environments/dev

    outputs:
      dev: ${{ steps.get-dev.outputs.bucket}}

  synchronize-bucket-folder-dags-dev:
    needs: get-composer-buckets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Synchronize Cloud Composer bucket folder dags/ in dev
      run: gsutil -m rsync -d -r  -x ".*\.md$" dags gs://${{ needs.get-composer-buckets.outputs.dev }}
