name: dbt

on:
  push:
    branches:
      - main
    paths:
      - 'dbt/**.sql'
      - 'dbt/**.yml'
      - config-files/composer-bucket-*

permissions:
  contents: read

jobs:
  get-composer-buckets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install jq
        run: sudo apt install -y jq

      - id: get-dev
        name: Get Cloud Composer bucket for dev
        run: echo "::set-output name=bucket::$(terraform output -json | jq -r '.airflow_dags_gcs_prefix.value' | sed "s/dags/data\/dbt/")"
          working-directory: terraform/environments/dev

    outputs:
      dev: ${{ steps.get-dev.outputs.bucket}}

  synchronize-bucket-folder-dbt-dev:
    needs: get-composer-buckets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Synchronize GCS bucket folder dbt/
      run: gsutil -m rsync -d -r  -x ".*\.md$" dbt gs://${{ needs.get-composer-buckets.outputs.dev }}
