name: Python Linter

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.py'
  push:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
